// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dsl.proto

package spec

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Query_Type int32

const (
	Query_TERM   Query_Type = 0
	Query_AND    Query_Type = 1
	Query_OR     Query_Type = 2
	Query_DISMAX Query_Type = 3
)

var Query_Type_name = map[int32]string{
	0: "TERM",
	1: "AND",
	2: "OR",
	3: "DISMAX",
}

var Query_Type_value = map[string]int32{
	"TERM":   0,
	"AND":    1,
	"OR":     2,
	"DISMAX": 3,
}

func (x Query_Type) String() string {
	return proto.EnumName(Query_Type_name, int32(x))
}

func (Query_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{0, 0}
}

type Query struct {
	Queries    []*Query   `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	Type       Query_Type `protobuf:"varint,2,opt,name=type,proto3,enum=spec.Query_Type" json:"type,omitempty"`
	Field      string     `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	Value      string     `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Not        *Query     `protobuf:"bytes,5,opt,name=not,proto3" json:"not,omitempty"`
	Tiebreaker float32    `protobuf:"fixed32,6,opt,name=tiebreaker,proto3" json:"tiebreaker,omitempty"`
	Boost      float32    `protobuf:"fixed32,7,opt,name=boost,proto3" json:"boost,omitempty"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e64ff22355f731d, []int{0}
}
func (m *Query) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Query.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return m.Size()
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetQueries() []*Query {
	if m != nil {
		return m.Queries
	}
	return nil
}

func (m *Query) GetType() Query_Type {
	if m != nil {
		return m.Type
	}
	return Query_TERM
}

func (m *Query) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Query) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Query) GetNot() *Query {
	if m != nil {
		return m.Not
	}
	return nil
}

func (m *Query) GetTiebreaker() float32 {
	if m != nil {
		return m.Tiebreaker
	}
	return 0
}

func (m *Query) GetBoost() float32 {
	if m != nil {
		return m.Boost
	}
	return 0
}

func init() {
	proto.RegisterEnum("spec.Query_Type", Query_Type_name, Query_Type_value)
	proto.RegisterType((*Query)(nil), "spec.Query")
}

func init() { proto.RegisterFile("dsl.proto", fileDescriptor_3e64ff22355f731d) }

var fileDescriptor_3e64ff22355f731d = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0xc3, 0x30,
	0x18, 0x80, 0x9b, 0xb6, 0x6b, 0xdd, 0x3f, 0x90, 0x12, 0x3c, 0x04, 0xc1, 0x50, 0x86, 0x42, 0x2f,
	0xeb, 0x60, 0x3e, 0xc1, 0x64, 0x1e, 0x3c, 0x4c, 0x31, 0xee, 0xe0, 0x75, 0xdd, 0xfe, 0xd5, 0x62,
	0x35, 0xb5, 0x4d, 0x85, 0xde, 0x7d, 0x00, 0x1f, 0xcb, 0xe3, 0x8e, 0x1e, 0xa5, 0x7d, 0x11, 0x49,
	0x8a, 0x30, 0xbc, 0xe5, 0xfb, 0xbe, 0xe4, 0x4f, 0x08, 0x0c, 0xb7, 0x55, 0x1e, 0x17, 0xa5, 0x54,
	0x92, 0xba, 0x55, 0x81, 0x9b, 0xd3, 0x49, 0x9a, 0xa9, 0xa7, 0x3a, 0x89, 0x37, 0xf2, 0x65, 0x9a,
	0xca, 0x54, 0x4e, 0x4d, 0x4c, 0xea, 0x9d, 0x21, 0x03, 0x66, 0xd5, 0x1f, 0x1a, 0x7f, 0xd8, 0x30,
	0xb8, 0xaf, 0xb1, 0x6c, 0xe8, 0x05, 0xf8, 0x6f, 0x35, 0x96, 0x19, 0x56, 0x8c, 0x84, 0x4e, 0x34,
	0x9a, 0x8d, 0x62, 0x3d, 0x30, 0x36, 0x55, 0xfc, 0x35, 0x7a, 0x0e, 0xae, 0x6a, 0x0a, 0x64, 0x76,
	0x48, 0xa2, 0xe3, 0x59, 0x70, 0xb0, 0x27, 0x5e, 0x35, 0x05, 0x0a, 0x53, 0xe9, 0x09, 0x0c, 0x76,
	0x19, 0xe6, 0x5b, 0xe6, 0x84, 0x24, 0x1a, 0x8a, 0x1e, 0xb4, 0x7d, 0x5f, 0xe7, 0x35, 0x32, 0xb7,
	0xb7, 0x06, 0xe8, 0x19, 0x38, 0xaf, 0x52, 0xb1, 0x41, 0x48, 0xfe, 0x5f, 0xaa, 0x3d, 0xe5, 0x00,
	0x2a, 0xc3, 0xa4, 0xc4, 0xf5, 0x33, 0x96, 0xcc, 0x0b, 0x49, 0x64, 0x8b, 0x03, 0xa3, 0x87, 0x26,
	0x52, 0x56, 0x8a, 0xf9, 0x26, 0xf5, 0x30, 0x9e, 0x80, 0xab, 0x9f, 0x43, 0x8f, 0xc0, 0x5d, 0x5d,
	0x8b, 0x65, 0x60, 0x51, 0x1f, 0x9c, 0xf9, 0xed, 0x22, 0x20, 0xd4, 0x03, 0xfb, 0x4e, 0x04, 0x36,
	0x05, 0xf0, 0x16, 0x37, 0x0f, 0xcb, 0xf9, 0x63, 0xe0, 0x5c, 0xb1, 0xaf, 0x96, 0x93, 0x7d, 0xcb,
	0xc9, 0x4f, 0xcb, 0xc9, 0x67, 0xc7, 0xad, 0x7d, 0xc7, 0xad, 0xef, 0x8e, 0x5b, 0x89, 0x67, 0xfe,
	0xe9, 0xf2, 0x37, 0x00, 0x00, 0xff, 0xff, 0x37, 0x4d, 0x5b, 0x50, 0x69, 0x01, 0x00, 0x00,
}

func (m *Query) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Query) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Query) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Boost != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Boost))))
		i--
		dAtA[i] = 0x3d
	}
	if m.Tiebreaker != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Tiebreaker))))
		i--
		dAtA[i] = 0x35
	}
	if m.Not != nil {
		{
			size, err := m.Not.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDsl(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintDsl(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Field) > 0 {
		i -= len(m.Field)
		copy(dAtA[i:], m.Field)
		i = encodeVarintDsl(dAtA, i, uint64(len(m.Field)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Type != 0 {
		i = encodeVarintDsl(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Queries) > 0 {
		for iNdEx := len(m.Queries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Queries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDsl(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintDsl(dAtA []byte, offset int, v uint64) int {
	offset -= sovDsl(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Query) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Queries) > 0 {
		for _, e := range m.Queries {
			l = e.Size()
			n += 1 + l + sovDsl(uint64(l))
		}
	}
	if m.Type != 0 {
		n += 1 + sovDsl(uint64(m.Type))
	}
	l = len(m.Field)
	if l > 0 {
		n += 1 + l + sovDsl(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovDsl(uint64(l))
	}
	if m.Not != nil {
		l = m.Not.Size()
		n += 1 + l + sovDsl(uint64(l))
	}
	if m.Tiebreaker != 0 {
		n += 5
	}
	if m.Boost != 0 {
		n += 5
	}
	return n
}

func sovDsl(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDsl(x uint64) (n int) {
	return sovDsl(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Query) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDsl
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Query: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Query: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Queries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDsl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDsl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDsl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Queries = append(m.Queries, &Query{})
			if err := m.Queries[len(m.Queries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDsl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= Query_Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDsl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDsl
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDsl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Field = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDsl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDsl
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDsl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Not", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDsl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDsl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDsl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Not == nil {
				m.Not = &Query{}
			}
			if err := m.Not.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tiebreaker", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Tiebreaker = float32(math.Float32frombits(v))
		case 7:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Boost", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Boost = float32(math.Float32frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipDsl(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDsl
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthDsl
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDsl(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDsl
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDsl
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDsl
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDsl
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthDsl
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowDsl
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipDsl(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthDsl
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthDsl = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDsl   = fmt.Errorf("proto: integer overflow")
)
